# Generated by Django 2.1.4 on 2019-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='Cabin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='titanic',
            name='Survived',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
